name: 'Android Testify Action'
description: 'GitHub Action for running Android Testify screenshot tests'
author: 'ndtp'

inputs:

  module: # "$MODULE"
    description: The gradle project module name. e.g. `:app`
    required: true

  app_apk: # "$APP_APK"
    description: The full path to the application apk under test. For library projects, this will be the test apk.
    required: true

  app_package: # "$APP_PACKAGE"
    description: The package name of the app. For example, `com.sample`
    required: true

  test_apk: # "$TEST_APK"
    description: The file name of the test runner .apk
    required: true

  test_package: # "$TEST_PACKAGE"
    description: The package name of test runner .apk
    required: true

  test_runner: # "androidx.test.runner.AndroidJUnitRunner"
    description: The fully qualified class name for the Instrumentation test runner. e.g. `androidx.test.runner.AndroidJUnitRunner`
    required: true

  device_density: # "$DEVICE_DENSITY"
    description: DPI value to set on the emulator
    required: false

  animations:
    description: Enable animations on the emulator
    required: true

  show_ime_with_hard_keyboard:
    description: Show the onscreen keyboard (IME)
    required: true

  show_passwords:
    description: Show password entry characters
    required: true

  verbose:
    description: You can enable the verbose log for easier debugging.
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run action script
      shell: bash
      run: |
        echo "GITHUB_WORKSPACE:${GITHUB_WORKSPACE}"
        echo "======="
        echo "pwd:"
        pwd
        echo ""
        echo "======="
        echo "find . | grep action.sh"
        find . | grep action.sh
        echo ""
        echo "======="
        echo "github.action_path"
        echo "${{ github.action_path }}"

        echo "run action.sh"
        "${{ github.action_path }}/action.sh" ${{ inputs.animations }} ${{ inputs.app_apk }} ${{ inputs.app_package }} ${{ inputs.device_density }} ${{ inputs.module }} ${{ inputs.show_ime_with_hard_keyboard }} ${{ inputs.show_passwords }} ${{ inputs.test_apk }} ${{ inputs.test_package }} ${{ inputs.test_runner }} ${{ inputs.verbose }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshot-test-results
        path: |
          screenshot-test-logcat.log
          ./output/
          "./app/build/outputs/androidTest-results/connected/**/*.xml"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Screenshot Tests
        path: "./app/build/outputs/androidTest-results/connected/debug/*.xml"
        reporter: java-junit

branding:
  icon: 'check-circle'
  color: 'green'
